# Generated by Django 3.1.4 on 2020-12-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcopy',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='imagegalery',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
