# Generated by Django 3.1.4 on 2020-12-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_auto_20201208_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegalery',
            name='img',
            field=models.ImageField(default='img2', upload_to='images'),
        ),
    ]
