# Generated by Django 3.1.4 on 2020-12-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_imagegalery_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegalery',
            name='img',
        ),
        migrations.AlterField(
            model_name='adcopy',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='picturs'),
        ),
        migrations.AlterField(
            model_name='imagegalery',
            name='image',
            field=models.ImageField(default='', upload_to='picturs'),
        ),
    ]
