# Generated by Django 3.1.4 on 2020-12-05 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('number_of_used_limite', models.IntegerField(default=0)),
                ('number_of_used', models.IntegerField(default=0)),
                ('trying_period', models.IntegerField(default=0)),
                ('duration_unite', models.CharField(choices=[('M', 'month'), ('D', 'day'), ('Y', 'Year')], default='D', max_length=1)),
                ('trying_period_price', models.IntegerField(default=0)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('benifiters', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_duration', models.CharField(choices=[('m', 'month'), ('s', 'six months'), ('y', 'year')], max_length=1)),
                ('subscription_from', models.DateTimeField()),
                ('subscription_to', models.DateTimeField()),
                ('paid', models.BooleanField(default=False)),
                ('price', models.FloatField(default=12.49)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='settingModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_join_per_time', models.IntegerField(default=20)),
                ('post_per_time', models.IntegerField(default=15)),
                ('to_wait_after_each_join', models.IntegerField(default=5)),
                ('to_wait_after_each_post', models.IntegerField(default=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_status', models.CharField(default='unactive', max_length=20)),
                ('coupon_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.coupon')),
                ('profile_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.subscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
